### ISSUE TITLE
Freenas replication task incompatible to autozsys_* snapshot naming scheme

### ISSUE THREAD

**Issue by satoshishop** [ubuntu/zsys#106]
**Describe the bug**
Your snapshot naming scheme breaks compatibility to the freenas snapshot replication task.
Freenas requires snapshot names to contain the creation date.

Freenas snapshots:
manual-%Y-%m-%d_%H-%M 
auto-%Y-%m-%d_%H-%M 

zfs auto snap snapshots:
zfs-auto-snap_recent-%Y-%m-%d-%H%M
zfs-auto-snap_hourly-%Y-%m-%d-%H%M
zfs-auto-snap_daily-%Y-%m-%d-%H%M
zfs-auto-snap_weekly-%Y-%m-%d-%H%M
zfs-auto-snap_monthly-%Y-%m-%d-%H%M

**Screenshots**
https://kopano.mariokuschel.info/owncloud/s/5BdcvwvsX2or7gz

**Comment by didrocks** [comment]
I think that freenas zfs-auto-snap configuration should be tweakable to match different naming scheme.

Indeed, I don’t expect that anyone doing manual snapshots to always follow the `manual_` scheme or that all tools will use auto-.
In addition, the issue with this scheme is that it translates badly with timezone configuration and multiple independant user snapshots can be merged together as a single state when they were actually 2 different ones.

One think we can do is optionally make the name tweakable in our configuration, but I suggest you open a bug as well on Freenas auto snapshot tool to that it doesn’t hardcode it as well.

**Comment by psy0rz** [comment]
I think thats a freenas bug. As far as i can see, zsys uses "autozsys_..." as its naming scheme?

Freenas and other tools should just ignore other snapshots.

Also checkout https://github.com/psy0rz/zfs_autobackup if you want to do replication that works a bit better in this usecase. (shameless plug :)

**Comment by didrocks** [comment]
> I think thats a freenas bug. As far as i can see, zsys uses "autozsys_..." as its naming scheme?

That’s correct :)

**Comment by jibel** [comment]
I second what didrocks and psy0rz said. It should be updatable on Freenas's side to prevent collisions with other systems or just be ignored if not recognized by Freenas. I'm closing this report.

Do not hesitate to submit any issue you may find with zsys.

**Comment by danielkrajnik** [comment]
@didrocks Is it possible for a user to change zsys naming scheme to include creation date? I think that knowing when a snapshot was created would be really helpful. Could it be modified in zsys.conf or anywhere else?
