### ISSUE TITLE
Enable trim support and update people to use it.

### ISSUE THREAD

**Issue by didrocks** [ubuntu/zsys#122]
We should enable autotrim on user’s disk, even on 20.04

**Comment by psy0rz** [comment]
yes..i checked it directly after installing and was surprised it was disabled.

**Comment by jibel** [comment]
The change has been release to Ubuntu Groovy
*ubiquity (20.10.1) groovy; urgency=medium

  [ Jean-Baptiste Lallement ]
  * zsys-setup: Enable autotrim on all pools.
