### ISSUE TITLE
Document general behaviour

### ISSUE THREAD

**Issue by psy0rz** [ubuntu/zsys#147]
I'm trying to backup my desktop with [zfs-autobackup,](https://github.com/psy0rz/zfs_autobackup) but it seems i now have two sets of "ubuntu_..." sets of filesystems?

I would guess this is because i reverted to a previous snapshot via grub?

I would be very helpfull if you could document the general behaviour of zsysctl:

- What are the naming schemes of datasets and snapshots?
- What happens if I select a filesystem to restore or boot from in grub? Are datasets cloned/renamed etc
- How to automatically create snapshots and when/how will they be destroyed? (i saw a .timer service)
- Are all snapshots selectable in grub? (i saw some of my own snapshots)
- What are the consequences if i select a snapshot in grub that doesn't exist for all datasets?
- Do you have any general tips or thoughts about what a snapshot/backup tool can do to prevent any problems or conflicts? 

I understand this tool is still in development, so dont take this as criticism :)

Thanks!

**Comment by didrocks** [comment]
No worry, the good news is that there is a blog post series that I’m currently publishing that exactly answers it all! :)

You can follow it on my blog (published on planet.ubuntu.com as well): https://didrocks.fr/.
I think all of the above questions will be answered in the 9 part series I’m planning (publishing on Tuesday and Thursday).

If you wish to contribute by turning part of this as wiki pages on this repo, that would be awesome!

If, once the whole blog post is done, there are still some unanswered questions, do not hesitate to ping here. Meanwhile, do you mind if I close this?

**Comment by psy0rz** [comment]
I just checked and it looks awesome! I would say: At least link to it from the readme.

When i have time i'll read up on it and i'll let you know if i have any questions. Thanks.

**Comment by didrocks** [comment]
Good idea, once all done, I’ll link the serie from the readme!

**Comment by psy0rz** [comment]
I've read the blog until the last one and a lot of stuff has become clear. Will you shed some light on the naming suffixes in a future one?

It will be very interesting to extend zfs-autobackup to backup everything correctly, especially clones which are later promoted or "demoted" when a user boots a different state. And offcourse the properties which can change after a backup of a snapshot is made.

**Comment by didrocks** [comment]
Thanks a lot! I don’t think there is anything magic on the naming suffix, those are just hash keys generated with a fix length to avoids collision.

Excellent news if you can extend zfs-autobackup! Let me know if there is any question or anything else to answer :)
