### ISSUE TITLE
armhf tests are not passing

### ISSUE THREAD

**Issue by rafaeldtinoco** [ubuntu/zsys#157]
**0.5.0 armhf regression when MachinesToGolden() is called for comparison **

Hello, this is @rafaeldtinoco and I'm on maint+1 week. When doing my daily maintenance I saw that zsys is FTBFS in armhf:

http://qa.ubuntuwire.org/ftbfs/

zsys execute "go tests" when compiling the Debian binary package. Because of that, it was found an issue, likely related to the *test*:

"assertMachinesToGolden()" is triggered from many tests because of "assertMachinesEquals()" is triggered. Example: https://gist.github.com/rafaeldtinoco/b5981bc949a0a52e7e08fe8a16e713f0

It looks to me that machines.state is emptied when m1 and m2 are compared... but I'll let developers to understand reasons better.

**To Reproduce**
1. Get an armhf container, make sure zfs related services are disabled
2. build-dep zsys dependencies
3. dpkg-buildpackage -us -uc -b 

**Expected behavior**
It should pass the tests for all supported architectures OR the binary package should be removed from the archive (and not generated any more) for unsupported arches.

**Installed versions:**
 - OS: Focal and Groovy with latest updates (built in an armhf container in arm64 HW)
- Zsysd running version: none =)

**Additional context**
#ubuntu-devel -> rafaeldtinoco

**Comment by didrocks** [comment]
armhf has been removed many cycles ago (so it’s not technically a regression), but it’s something we should look once we have the time to deal with it.
