### ISSUE TITLE
Building and Installing

### ISSUE THREAD

**Issue by borgmanJeremy** [ubuntu/zsys#158]
I was interested in building and installing this on arch linux but I don't see and compiling and installation directions.

**Comment by didrocks** [comment]
This is a standard go project, hence no instruction for installing it, but we can add a wiki page for this with the help of the community.

Basically, it’s `go build ./...` to build any necessary binary, a single binary is then needed.

**Comment by borgmanJeremy** [comment]
Ok thanks. Does it expect a specific zfs dataset layout?

**Comment by didrocks** [comment]
It does! Everything is detailed in a 10 blog post series about the specificities of ZSys: https://didrocks.fr/. This should shed some lights on the functionalities and how this works.

**Comment by borgmanJeremy** [comment]
Oh perfect, this is exactly the type of info I was looking for. Thanks for the help!

**Comment by Lockszmith** [comment]
> ... Everything is detailed in a **10 blog** post series ...

Browsing to https://didrocks.fr/tags/zfs/ returns only 9 posts, can you point to the missing one?

**Comment by didrocks** [comment]
sorry, I miscounted. There were only 9 this cycle :)
