### ISSUE TITLE
zsys post-installation script failed during upgrade of broken ZSYS installation

### ISSUE THREAD

**Issue by almereyda** [ubuntu/zsys#159]
When upgrading zsys via apt, the unit is left in dead state, resulting in the post-upgrade hook to fail.

1. `apt update`
2. `apt upgrade` 0.4.5 > 0.4.6
4. At the very end of the output, it says:

```
Fehler traten auf beim Bearbeiten von:
 zsys
ZSys is adding automatic system snapshot to GRUB menu
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

No further signs of failure were immediately visible.

Instead of being presented with an error, it is expected of the `90_zsys_system_autosnapshot` hook to create a new snapshot and add it to the GRUB menu.

Further details of `/tmp/report` and entries from `/var/log/apt/term.log` live in https://gist.github.com/almereyda/74598a5e8972d20cde084f0fc1d5522c/edit

 - OS: Ubuntu 20.04
- Zsysd running version: 0.4.6

* `zsys-system-autosnapshot` and `90_zsys_system_autosnapshot` are in the state of 9c4d63a
* Running the commands in the hook (`snapshot`, `update-grub`) manually succeeded without error. This was done to prevent ending up in a previous system state after reboot.
* `bpool` is not imported, and `/boot` is mounted from the current `rpool/ROOT/ubuntu_vno50r`
* apt's term.log has frequent entries of potentially managed, but inexisting datasets of the kind `bpool/BOOT/ubuntu_vno50r@autozsys_xxxxxx`, since their pool is not imported.

Which leaves me wondering, why `bpool` is present, but not imported and expected to be there, but not used since the beginning of this system's installation. As `/tmp/report` reports:

```
SystemdFailedUnits:
 Error: command ['systemctl', 'status', '--full', 'boot.mount'] failed with exit code 3: ● boot.mount - /boot
      Loaded: loaded (/etc/zfs/zfs-list.cache/bpool; generated)
      Active: failed (Result: exit-code) since Tue 2020-07-14 22:07:30 CEST; 1 weeks 1 days ago
       Where: /boot
        What: bpool/BOOT/ubuntu_vno50r
        Docs: man:zfs-mount-generator(8)
 
 Jul 14 22:07:30 acacia systemd[1]: Mounting /boot...
 Jul 14 22:07:30 acacia mount[1686]: filesystem 'bpool/BOOT/ubuntu_vno50r' cannot be mounted, unable to open the dataset
 Jul 14 22:07:30 acacia systemd[1]: boot.mount: Mount process exited, code=exited, status=1/FAILURE
 Jul 14 22:07:30 acacia systemd[1]: boot.mount: Failed with result 'exit-code'.
 Jul 14 22:07:30 acacia systemd[1]: Failed to mount /boot.
```

This behaviour correlates with the initial installation of ZSYS 0.4.5 on 22.04.2020 with the associated entry in `term.log`. Please also refer to the `boot.mount` journal in the gist.

Yet `grub` is known to be serving kernels and initrd from the `rpool` since a system upgrade (including grub, but nothing ZFS related) on 03.04.2020, despite the boot unit continued to work just fine until ZSYS was present.

Gladly `update-grub` always found the kernels and initrds in the `rpool`, and the system boots just fine.

What is it that I am witnessing here, that got surfaced by the ZSYS error during the recent upgrade?

**Comment by almereyda** [comment]
Since `bpool` is not mounted, also `update-grub` cannot finish its work. Seems the underlying issue is documented in

- https://www.reddit.com/r/zfs/comments/fzbi1h/zfs_on_linux_grub_cannot_update_with_zfs_on_root/
- https://askubuntu.com/questions/1245549/ubuntu-20-04-on-zfs-cant-update-kernel-bpool-missing
- https://github.com/openzfs/zfs/issues/9801
- https://bugs.launchpad.net/ubuntu/+source/os-prober/+bug/1848496

and propagated all the way up to ZSYS. The Ask Ubuntu link explains it quite well.

**Comment by didrocks** [comment]
Thanks for your bug report and the detailed bug report, with links and pointers, this is awesome :)

Indeed, it seems the issues appears on systems where vdev changed at startup, we should at least not make the postinst fail and issue a warning to unblock users.

We’ll look at the best course of action for this.

There is no official timeline yet to get ZSys out its experimental state.
