### ISSUE TITLE
Need to rename rpool/USERDATA for home dirs to automount

### ISSUE THREAD

**Issue by armarti** [ubuntu/zsys#2]
I'm sure the Ubuntu team will iron this out before anything's released, but just for anyone else trying to get 20.04 to automount their homedirs after using the Ubiquity ZFS installer, you need to rename `rpool/USERDATA` to something else, e.g.:

    zfs rename rpool/USERDATA rpool/ROOT

The `canmount` property of all (case-insensitive) "\*/userdata/\*" datasets is [always set to "noauto"](https://github.com/ubuntu/zsys/blob/5e52a3c5032fb7011d0891979a9529326de9a526/internal/zfs/zfs.go#L320) on boot.

**Comment by armarti** [comment]
@ubuntu feel free to close this if you like.

**Comment by didrocks** [comment]
doing so :)
