### ISSUE TITLE
Generate menu entries by loading grub.cfg from new boot environment

### ISSUE THREAD

**Issue by ne9z** [ubuntu/zsys#201]
As I understands it, in order to add boot environment menu entries, zsys needs to scan initrd & ucode in the newly created boot environments. This is not necessary and time consuming.

If `/boot/grub` is inside `/BOOT/ubuntu-currentUUID` and cloned as part of the system state, to add a boot environment entry is as simple as:

- adding GRUB command `configfile ($root)/BOOT/ubuntu-newUUID@/grub/grub.cfg` to `/BOOT/ubuntu-currentUUID@/grub/grub.cfg`
- replace all occurrences of `ubuntu-currentUUID` with `ubuntu-newUUID` in `/BOOT/ubuntu-newUUID@/grub/grub.cfg`

No initrd/ucode detection needed. 

A sample menu file is the following:
```
echo 'Loading boot environment menu'
submenu 'Fri Mar 19 15:01 2021 post_-S_--noconfirm_vim' {
configfile ($root)/sys/BOOT/pac-eashcq@/grub/grub.cfg
}
submenu 'Fri Mar 19 15:01 2021 pre__-S_--noconfirm_vim' {
configfile ($root)/sys/BOOT/pac-tqgmly@/grub/grub.cfg
}
```

Moved from [this issue](https://github.com/openzfs/openzfs-docs/issues/147)

**Comment by didrocks** [comment]
Hey, thanks for reaching out.

This is not as simple as you think: we don’t only add an entry for the current machine state, but for the whole history, which means, recreate machines that were available in the past with the exact `/etc`, `/boot` and other `\` equivalent dataset on that time.

You can disable this script detection by simply removing zsys from your system, and you will lose that feature, but the detection will be, ofc, faster as it needs only to scan one entry.

However, if you still think you can get correct entries with a way simpler script, feel free to propose a PR. Note that all tests of https://github.com/ubuntu/grubzfs-testsuite/ should pass to have all the features and corner cases covered.

**Comment by ne9z** [comment]
@didrocks 

Actually I implemented this for Arch Linux, it does create menu entries for the entire history. Feel free to try out [bieaz](https://gitlab.com/m_zhou/bieaz) and its companion [Root on ZFS installation guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Arch%20Linux%20Root%20on%20ZFS.html).

**Comment by didrocks** [comment]
Yes, but from your description:
```
Only `/boot/{efi,efis}` can be on a non-ZFS (vfat) partition, all other data must be managed by ZFS.

`/boot/grub` must be inside the same ZFS dataset as `/boot`. Or else GRUB menu will not work.
```

This is not the case in ubuntu default installation (as written above), which is what adds a bunch of complexity in the layout. Also, the layout can evolve over time, which we do support.

**Comment by ne9z** [comment]
Well I think putting `/boot/grub` in EFI system partition is a bit of curiosity ;) and more complex than in bpool. Just my two cents.

**Comment by ne9z** [comment]
@didrocks On a separate note, official (as published by openzfs-docs) [Ubuntu on ZFS guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/Ubuntu/Ubuntu%2020.04%20Root%20on%20ZFS.html#step-4-system-configuration) also does `/boot/grub` in `bpool` for multi-disk installation.
```
Put /boot/grub on the EFI System Partition:

For a single-disk install only:

...
```

**Comment by didrocks** [comment]
Right, but this guide (and so, this setup) is not maintained, nor officially supported, by Canonical.
