### ISSUE TITLE
Cannot recover from "ERROR couldn't save system state: Minimum free space to take a snapshot and preserve ZFS performance is 20%. Free space on pool "bpool" is 15%."

### ISSUE THREAD

**Issue by pjgoodall** [ubuntu/zsys#208]
**Describe the bug**
In the last week the normal zsys sytem snapshot process associated with updating packages on my system fails with the following error message:

```
ERROR couldn't save system state: Minimum free space to take a snapshot and preserve ZFS performance is 20%.
Free space on pool "bpool" is 15%.
```

I have tried `zsysctl service gc --all` with no improvement. I have tried removing the oldest snapshots manually - no change to the problem. Advice on web forums seem very hit and miss - I have no confidence in 'experimental' fixes. Diagnostic advice is very sparse.

I have been using this system for about a year without any great difficulty

**To Reproduce**
Change any package state that would normally cause a zsys snapshot to be taken.

**Expected behavior**
A system snapshot to be taken when package install state is changed

**For ubuntu users, please run and  copy the following:**
1. `ubuntu-bug zsys --save=/tmp/report`
2. Copy paste below `/tmp/report` content:
```
I'd rather someone contacted me for this report. I don't really feel it is secure to make it public - a lot of system information.
```

**Screenshots**

**Installed versions:**
 - OS: (`/etc/os-release`)
 ```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

 ```
- Zsysd running version: (`zsysctl version` output)
```
zsysctl	0.4.8
zsysd	0.4.8
```

**Additional context**

**Comment by didrocks** [comment]
Hi, thanks for reporting this bug and sorry for this issue! This is related to issue #204 (I’ll dup it to that). Unfortunately, the best course of action right now is to `zsysctl state remove` manually some states (you can see the states id with `zsysctl show`). 

That way, you will free up some spaces manually in your bpool. Another way is to reduce the minimal number of snapshots to keep before doing your GC run (this is done in the configuration file).

**Comment by pjgoodall** [comment]
Thanks Didier,

I will try to help out with #204

—
