### ISSUE TITLE
Receiving error user doesn't exist.

### ISSUE THREAD

**Issue by JamesSeiters** [ubuntu/zsys#209]
**Describe the bug**
    I am receiving the error:
    ERROR couldn't save state for user "jseiters": user "jseiters" doesn't exist
    This occurs when doing a manual save and when a save is triggered by a timer.

**To Reproduce**
1. zsysctl save.
2. Get an error message.

**Expected behavior**
The user state for the currently logged-on user should be saved.

**For ubuntu users, please run and  copy the following:**
1. `ubuntu-bug zsys --save=/tmp/report`
2. Copy paste below `/tmp/report` content:
```
Attached as it is rather large.

[report.txt](https://github.com/ubuntu/zsys/files/6658652/report.txt)
```

**Installed versions:**
 - OS: (`/etc/os-release`)
       NAME="Ubuntu"
       VERSION="20.04.2 LTS (Focal Fossa)"
       ID=ubuntu
       ID_LIKE=debian
       PRETTY_NAME="Ubuntu 20.04.2 LTS"
       VERSION_ID="20.04"

- Zsysd running version: (`zsysctl version` output)
       zsysctl 0.4.8
       zsysd   0.4.8

**Additional context**
This is a workstation that was installed following the instructions from the OpenZFS github. The second user (jamesspg) was added using the KDE GUI.

I am including some errors from journalctl that may be relevant. The problem seems to have started from the very beginning. The second user that was added after installation does not have this error.

This is the first boot into the new system before step 6 in section 6 of the installation instructions.
Feb 28 07:47:13 ITWorkDesk00001 useradd[7048]: new user: name=jseiters, UID=1000, GID=1000, home=/home/jseiters, shell=/bin/bash, from=/dev/tty1
Feb 28 07:47:19 ITWorkDesk00001 passwd[7056]: pam_unix(passwd:chauthtok): password changed for jseiters
Feb 28 07:47:48 ITWorkDesk00001 chfn[7149]: changed user 'jseiters' information
Feb 28 07:48:48 ITWorkDesk00001 zsysd[7504]: level=warning msg="[[9b77168c:5f3d4fd8]] Couldn't destroy user dataset rpool/USERDATA/jseiters_d0nidq (due to rpool/USERDATA/jseiters_d0nidq): couldn't destroy \"rpool/USERDATA/jseiters_d0nidq\" and its children: cannot destroy dataset \"rpool/USERDATA/jseiters_d0nidq\": dataset is busy"
Feb 28 07:48:48 ITWorkDesk00001 zsysctl[7487]: WARNING Couldn't destroy user dataset rpool/USERDATA/jseiters_d0nidq (due to rpool/USERDATA/jseiters_d0nidq): couldn't destroy "rpool/USERDATA/jseiters_d0nidq" and its children: cannot destroy dataset "rpool/USERDATA/jseiters_d0nidq": dataset is busy

This is after the final reboot into the complete system with KDE GUI installed.
Feb 28 08:50:00 ITWorkDesk00001 systemd[1]: Started Session 3 of user jseiters.
Feb 28 08:50:01 ITWorkDesk00001 sddm-helper[11782]: Adding cookie to "/home/jseiters/.Xauthority"
Feb 28 08:50:01 ITWorkDesk00001 pulseaudio[11776]: Failed to open cookie file '/home/jseiters/.config/pulse/cookie': No such file or directory
Feb 28 08:50:01 ITWorkDesk00001 pulseaudio[11776]: Failed to load authentication key '/home/jseiters/.config/pulse/cookie': No such file or directory
Feb 28 08:50:01 ITWorkDesk00001 pulseaudio[11776]: Failed to open cookie file '/home/jseiters/.pulse-cookie': No such file or directory
Feb 28 08:50:01 ITWorkDesk00001 pulseaudio[11776]: Failed to load authentication key '/home/jseiters/.pulse-cookie': No such file or directory
Feb 28 08:50:09 ITWorkDesk00001 zsysd[12959]: level=warning msg="[[d8053aa9:e451d363]] Couldn't destroy user dataset rpool/USERDATA/jseiters_d0nidq (due to rpool/USERDATA/jseiters_d0nidq): couldn't destroy \"rpool/USERDATA/jseiters_d0nidq\" and its children: cannot destroy dataset \"rpool/USERDATA/jseiters_d0nidq\": dataset is busy"
Feb 28 08:50:09 ITWorkDesk00001 zsysctl[12904]: WARNING Couldn't destroy user dataset rpool/USERDATA/jseiters_d0nidq (due to rpool/USERDATA/jseiters_d0nidq): couldn't destroy "rpool/USERDATA/jseiters_d0nidq" and its children: cannot destroy dataset "rpool/USERDATA/jseiters_d0nidq": dataset is busy
Feb 28 08:51:36 ITWorkDesk00001 zsysd[38790]: jseiters
Feb 28 08:51:36 ITWorkDesk00001 zsysctl[38782]: level=error msg="couldn't save state for user \"jseiters\": user \"jseiters\" doesn't exist"

zsysctl show
Name:           rpool/ROOT/ubuntu_onwysc
ZSys:            true
Last Used:   current
History:        
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_kcv7kb
    Created on: 2021-06-14 17:43:19
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_omyoz3
    Created on: 2021-06-14 17:42:32
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_4yhs6v
    Created on: 2021-06-14 17:41:16
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_hf2p94
    Created on: 2021-06-14 17:40:12
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_btzci5
    Created on: 2021-06-14 14:51:57
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_k01f3f
    Created on: 2021-06-14 12:24:52
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_60sude
    Created on: 2021-06-14 12:23:50
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_cgcjrt
    Created on: 2021-06-14 12:07:50
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_c89lta
    Created on: 2021-06-14 11:50:55
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_jv8k4h
    Created on: 2021-06-13 11:11:41
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_ihx458
    Created on: 2021-06-11 08:51:53
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_0t3h88
    Created on: 2021-06-10 15:44:28
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_03khsu
    Created on: 2021-06-09 08:54:53
  - Name:       rpool/ROOT/ubuntu_onwysc@autozsys_9vm9eb
    Created on: 2021-06-07 13:50:12
Users:
  - Name:    jamesspg
    History: 
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_kcv7kb (2021-06-14 17:43:23)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_omyoz3 (2021-06-14 17:42:37)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_4yhs6v (2021-06-14 17:41:19)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_hf2p94 (2021-06-14 17:40:15)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_btzci5 (2021-06-14 14:52:01)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_k01f3f (2021-06-14 12:24:56)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_60sude (2021-06-14 12:23:53)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_cgcjrt (2021-06-14 12:07:54)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_c89lta (2021-06-14 11:51:00)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_jv8k4h (2021-06-13 11:11:46)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_ihx458 (2021-06-11 08:51:57)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_0t3h88 (2021-06-10 15:44:32)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_03khsu (2021-06-09 08:54:57)
     - rpool/USERDATA/jamesspg_h4xn0c@autozsys_9vm9eb (2021-06-07 13:50:16)
  - Name:    root
    History: 
     - rpool/USERDATA/root_onwysc@autozsys_kcv7kb (2021-06-14 17:43:22)
     - rpool/USERDATA/root_onwysc@autozsys_omyoz3 (2021-06-14 17:42:37)
     - rpool/USERDATA/root_onwysc@autozsys_4yhs6v (2021-06-14 17:41:20)
     - rpool/USERDATA/root_onwysc@autozsys_hf2p94 (2021-06-14 17:40:15)
     - rpool/USERDATA/root_onwysc@autozsys_btzci5 (2021-06-14 14:52:01)
     - rpool/USERDATA/root_onwysc@autozsys_k01f3f (2021-06-14 12:24:55)
     - rpool/USERDATA/root_onwysc@autozsys_60sude (2021-06-14 12:23:53)
     - rpool/USERDATA/root_onwysc@autozsys_cgcjrt (2021-06-14 12:07:54)
     - rpool/USERDATA/root_onwysc@autozsys_c89lta (2021-06-14 11:51:00)
     - rpool/USERDATA/root_onwysc@autozsys_jv8k4h (2021-06-13 11:11:46)
     - rpool/USERDATA/root_onwysc@autozsys_ihx458 (2021-06-11 08:51:56)
     - rpool/USERDATA/root_onwysc@autozsys_0t3h88 (2021-06-10 15:44:32)
     - rpool/USERDATA/root_onwysc@autozsys_03khsu (2021-06-09 08:54:58)
     - rpool/USERDATA/root_onwysc@autozsys_9vm9eb (2021-06-07 13:50:16)

**Comment by JamesSeiters** [comment]
I believe the issue was caused by the instructions on the ZOL GitHub. I just finished installing Ubuntu on a server using modified instructions and I am not receiving the error. This issue is not a bug with the software but with the instructions.

Is it possible to add the user now so zsysctl will stop throwing the error?

I modified the instructions as follows:

Original instructions:
UUID=$(dd if=/dev/urandom bs=1 count=100 2>/dev/null | tr -dc 'a-z0-9' | cut -c-6)
ROOT_DS=$(zfs list -o name | awk '/ROOT\/kubuntu_/{print $1;exit}')
zfs create -o com.ubuntu.zsys:bootfs-datasets=$ROOT_DS -o canmount=on -o mountpoint=/home/$NEWUSERNAME rpool/USERDATA/$NEWUSERNAME_$UUID
adduser $NEWUSERNAME

cp -a /etc/skel/. /home/$NEWUSERNAME
chown -R $NEWUSERNAME:$NEWUSERNAME /home/$NEWUSERNAME
usermod -a -G adm,cdrom,dip,lpadmin,lxd,plugdev,sambashare,sudo $NEWUSERNAME

Instructions I entered:
UUID=$(dd if=/dev/urandom bs=1 count=100 2>/dev/null | tr -dc 'a-z0-9' | cut -c-6)
ROOT_DS=$(zfs list -o name | awk '/ROOT\/kubuntu_/{print $1;exit}')

adduser $NEWUSERNAME

usermod -a -G adm,cdrom,dip,lpadmin,lxd,plugdev,sambashare,sudo $NEWUSERNAME

**Comment by didrocks** [comment]
Thanks for reaching out! Now that your system is properly installed, you can add users with just `adduser`. The patch in ubuntu will create datasets in the correct directory and layout, with tags.

(I’m closing thus this bug as this was a setup issue)
