### ISSUE TITLE
Reverting doesn't work in Mint

### ISSUE THREAD

**Issue by mauricev** [ubuntu/zsys#217]
**Describe the bug**
It's not clear where this bug report should go. Reverting within the Grub environment in Linux mint (with ZFS  installed) doesn't work. The revert command is ignored. Who's responsible for the History menu in GRUB working?

**To Reproduce**
1 Setup a Linux Mint installation with ZFS root
2 Add a package to have ZSys create a ZFS snapshot. (or don't even use Zsys but just create one manually). _Something_ has to be responsible for setting up and handling the GRUB history menu, so I am just guessing this is done by ZSys. 
3 Attempt to revert to the created snapshot. This fails. No revert takes place.

**Expected behavior**
System should revert to the snapshot

**For ubuntu users, please run and  copy the following:**
Doesn't work in Mint.
```


**Installed versions:**
 NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

zsysctl	0.4.8
zsysd	0.4.8

**Comment by didrocks** [comment]
Thanks for reporting this bug!

Grub is handling the revert via a hook in zfs-linux package. I think you should file a patch on Mint against their zfs package directly so that they can cherry-pick patches in ubuntu and make it work again.

**Comment by mauricev** [comment]
I think you may have misunderstood my reason for posting here. I know you can't fix it. I’m trying to find where to post this bug. Mint doesn't seem have really any place to post bugs, let alone one specific to their ZFS package. I was hoping you might know, even know the responsible developer.

**Comment by didrocks** [comment]
I don’t, I work on ubuntu and know where to direct bugs to ubuntu, but not mint. Maybe try looking for a Mint user group?
