### ISSUE TITLE
Feature request: oddjob(-mkhomedir) functionality/replacement

### ISSUE THREAD

**Issue by averyfreeman** [ubuntu/zsys#43]
Thanks for the work on this, and all zfs-related things on Linux

I'd love to see zsys take the role of oddjob-mkhomedir for domain-connected systems where instead of automatically making home directories, individual zfs datasets could be made for users instead.

That could open up all sorts of per-user granularity for snapshots, clones, rollbacks, zfs send/receive, etc.

**Comment by didrocks** [comment]
Thanks for the feature request and feedbacks! Sorry, we were busy preparing the new release.
Indeed, what you write is mostly our goal where we want to take zsys.

However, I’m unsure what you mean by replacing oddjob-mkdhomedir? Creating per-user datasets automatically is what zsys is doing on ubuntu since 19.10 (if installed, ofc). Do you mean something different?

**Comment by averyfreeman** [comment]
Oh, does zsys already make a new user dataset every time a new user is created?  I was under the impression it was only for the user who was entered during the install process.

If so, I apologize for not noticing!

**Comment by didrocks** [comment]
No worry. Yes, it does on zsys systems. Closing thus.

**Comment by rejsmont** [comment]
It does, but only for *local* users. Users that are not added by `adduser` do not have ZFS datasets created. It would be awesome to have ZFS datasets created for users authenticated is via sssd.

**Comment by jibel** [comment]
This is correct. It does only for local users created with adduser/useradd not for home directories created via over methods like pam_mkhomedir or oddjob-mkhomedir.

Zsys provides a command to create userdata with "zsysctl userdata create". The home dataset must then be populated with the default skeleton and the right permissions which is basically what a pam_zsys module would do.

pam_zsys is an interesting way to achieve that. It would factorize the code into a single pam module, but I'm not sure how well it would integrate with other modules as they usually do other actions on the home directory than just creating it.

Another way to do it at the moment is to add support for zsys to *mkhomedir, these various methods would then do whatever they want with the just created home directory.

You can have a look at useradd.c (in package shadow) or adduser to see how it's been done there.

This is definitely something to consider but we need to give it more thoughts.
