### ISSUE TITLE
ERROR couldn't connect to zsys daemon: timed out waiting for server handshake

### ISSUE THREAD

**Issue by satmandu** [ubuntu/zsys#79]
I'm seeing occasional "ERROR couldn't connect to zsys daemon: timed out waiting for server handshake" messages.

I can get this to reliably appear if I do a ```zsysctl show```

One zfs system I have installed with 19.10 and upgraded to focal shows:
```
 zsysctl show
Name:      rpool/ROOT/ubuntu_wojf9o
ZSys:      false
Last Used: current
History:
Users:
```
The other machine shows this:
```
zsysctl show
ERROR couldn't connect to zsys daemon: timed out waiting for server handshake
```
However if I run it several minutes later the info is cached: 
```
Name:      rpool/ROOT/ubuntu_pzg8hb
ZSys:      true
Last Used: current
History:
  - Name:       rpool/ROOT/ubuntu_pzg8hb@autozsys_o2x8vm
    Created on: 2020-04-03 00:40:27
  - Name:       rpool/ROOT/ubuntu_pzg8hb@autozsys_einpzt
    Created on: 2020-04-02 20:13:39
```
and so on: https://paste.ubuntu.com/p/tMMmXmDVbJ/

**Comment by satmandu** [comment]
Also happening on software upgrades:
```
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
Refreshing boot menu
ERROR couldn't connect to zsys daemon: timed out waiting for server handshake 
```

**Comment by didrocks** [comment]
Do you have any segfault on zsysd when this happens? (like on bug #80). It’s like zsysd couldn’t start.

**Comment by satmandu** [comment]
Definitely looks like it is restarting:
```
sudo systemctl status zsysd
● zsysd.service - ZSYS daemon service
     Loaded: loaded (/lib/systemd/system/zsysd.service; static; vendor preset:>
     Active: active (running) since Mon 2020-04-06 12:01:29 EDT; 39s ago
TriggeredBy: ● zsysd.socket
   Main PID: 34252 (zsysd)
      Tasks: 8 (limit: 57596)
     Memory: 156.4M
     CGroup: /system.slice/zsysd.service
             └─34252 /sbin/zsysd

Apr 06 12:00:35 systemd[1]: Starting ZSYS daemon service...
Apr 06 12:01:29  systemd[1]: Started ZSYS daemon service.
```

**Comment by didrocks** [comment]
Every hour, there is a systemd user snapshot that is taken. I wonder how your timeout though.

Do you have some zsysd crash in /var/crash sometimes?

**Comment by didrocks** [comment]
please attach the journal logs when you hit a timeout

**Comment by satmandu** [comment]
I just realized I had an old ```10_linux_zfs``` backup in /etc/grub.d, and removing that is solving my issues, so I'm closing this. I'm no longer having issues.
