### ISSUE TITLE
Zsys as a potential storage backend for systemd-homed?

### ISSUE THREAD

**Issue by mskarbek** [ubuntu/zsys#84]
Systemd recently added `homed` as a new solution for `$HOME` dir management. Does Zsys team have any thoughts or interest in integration with `homed`? For quite obvious reasons OpenZFS can't be supported directly in `homed` but I have proposed integration mechanism using Varlink API in this comment: https://github.com/systemd/systemd/issues/15293#issuecomment-609684966. I would appreciate any feedback and eventual participation in discussion about the possible shape of such API if support for `homed` will become a desirable feature in Zsys.

**Comment by didrocks** [comment]
This isn’t in our initial roadmap.

I wouldn’t urge any systemd integration right now having already tried to work on systemd in the past (fsckd which was merged, and then reverted upstream without any strong objection basement), which we have to carry for years now on ubuntu and working well.

Note that we currently carry a patch to integrate with useradd, which covers server and desktop apps.

So, if systemd has some integration mechanism (can even be simpler integration point like executing a third-party binary), this would be doable. I’m happy to review any good patch with a testsuite over a stable systemd release supporting it.

**Comment by mskarbek** [comment]
My intent at this point is to only establish potential interest. I'm quite confident that without expressing any systemd devs won't provide any possibility for future integration so "just waiting for some" won't get us any further. I'm quite aware of the history between Ubuntu and systemd but I don't think that should impact potential future collaboration.

**Comment by jibel** [comment]
Thanks for rising this. There is nothing personal, but the response from Lennart in the thread you're referring to is quite clear and he is not interested in supporting ZFS with homed.
As Didier said working on the integration of ZFS with systemd-homed is not a priority for us either and our roadmap is already full for the coming development cycles.

**Comment by mskarbek** [comment]
That is why I have proposed a general approach that could benefit more than potential Zsys users. Having Lennart's response in mind I didn't want to pursue direct OpenZFS integration, but an open API that could be used to develop more potential storage backends for `homed`. If you think that this is not worthy of consideration then I respect that. Thanks for the response anyway.
