### ISSUE TITLE
No new dataset was created for a new user in ubuntu 20.04 - zsys 0.4.4

### ISSUE THREAD

**Issue by versus167** [ubuntu/zsys#94]
After 'apt update && apt dist-upgrade' today, I created a new user. But no new dataset was created for him. 

A problem with zsys or with other parts of ubuntu?

**Comment by didrocks** [comment]
Thanks for your bug report (did you have the template for filing a bug? It seems you didn’t fill it).

I indeed can confirm the issue and will dig into it today.

**Comment by versus167** [comment]
Yes, I had the template, but I didn't think it was strictly necessary in this case. Next time I will use it!

**Comment by didrocks** [comment]
FYI, this is now tracked in https://bugs.launchpad.net/ubuntu/+source/adduser/+bug/1873263 as it involved multiple components. The 3 packages are uploaded and should hit focal soon (finale freeze is today).

Closing as the zsys part of the code is now fixed.
Thanks a lot for this feedback, keep it coming :)

**Comment by versus167** [comment]
After today's update (zsys 0.4.5) and test with new user -> still no success - no new dataset was created :/

**Comment by didrocks** [comment]
Check the bug report I linked: adduser itself isn’t fixed released yet, it’s stuck when running tests in proposed.

If you are using gnome-control-center or adduser, this will thus not work until you get adduser 3.118ubuntu2.

**Comment by versus167** [comment]
Ah, ok thanks. Now I understand the relations between...
